#11 소나큐브 적용 (#47)
* #11 sonarqube github action build 추가

* #11 workflow branch 수정

* #11 workflow branch 수정

* #11 workflow branch 수정

* #11 build 수정

* #11 jacoco 추가

* #11 build 대신 test 로 변경

* #11 sonar 정보 gradle 에 추가

* #11 sonar properties 추가

* #11 sonar properties 추가

* #11 sonar scanner 로 변경

* #11 sonar scanner 로 변경

* #11 sonar scanner 로 변경

* #11 sonarqube 버전 변경

* #11 build test

* #11 scanner version 변경

* #11 scanner version 변경

* #11 scanner login/password 변경

* #11 limit coverage 0 으로 변경

* #11 limit coverage 43.64 으로 변경

* #11 jacoco report 변경

* #11 test coverage limit 변경

* #11 jacoco report 추가

* #11 coverage 변경

* #11 coverage 변경

* #11 lombok, config 는 test coverage 에서 제외

* #11 전체 coverage 0.5 로 변경

* #11 전체 coverage 0.5 로 변경

* #11 config 하위 클래스는 coverage 에서 제외

* #11 exception class를 coverage 에서 제외

* #11 coverage limit 해제

* #11 eof 추가

---------

Co-authored-by: hanjoo96.cho <hanjoo96.cho@navercorp.com>

diff --git a/.github/workflows/PullRequest.yml b/.github/workflows/PullRequest.yml
--- a/.github/workflows/PullRequest.yml
+++ b/.github/workflows/PullRequest.yml
@@ -25,6 +25,17 @@ jobs:
           overwrite-settings: true
           job-status: success
 
+      # Setup sonar-scanner
+      - name: Setup SonarQube
+        uses: warchant/setup-sonar-scanner@v5
+
+      - name: Cache SonarQube packages
+        uses: actions/cache@v1
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+
       - name: Cache gradle modules
         uses: actions/cache@v2
         with:
@@ -42,4 +53,54 @@ jobs:
         env:
           USERNAME: ${{secrets.USERNAME}}
           TOKEN: ${{secrets.TOKEN}}
-        run: ./gradlew build
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        run: ./gradlew clean test jacocoTestReport --stacktrace --profile
+
+      - name: SonarQube Scan
+        run: |
+          sonar-scanner \
+          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  \
+          -Dsonar.login=${{ secrets.SONAR_LOGIN }} \
+          -Dsonar.password=${{ secrets.SONAR_PASSWORD }} \
+          -Dsonar.projectKey=book-server \
+          -Dsonar.sourceEncoding=UTF-8 \
+          -Dsonar.language=java \
+          -Dsonar.java.source=11 \
+          -Dsonar.verbose=true \
+          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
+          -Dsonar.scm.provider=git \
+          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
+          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
+          -Dsonar.pullrequest.base=${{ github.base_ref }} \
+          -Dsonar.pullrequest.github.repository=${{ github.repository }} \
+          -Dsonar.sources=api/src \
+          -Dsonar.java.binaries=api/build/classes \
+          -Dsonar.log.level=INFO \
+
+      - name: Test Coverage
+        env:
+          USERNAME: ${{ secrets.USERNAME }}
+          TOKEN: ${{ secrets.TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        run: ./gradlew jacocoTestCoverageVerification --stacktrace --profile
+
+      - name: Add coverage to PR
+        id: jacoco
+        uses: madrapps/jacoco-report@v1.6.1
+        with:
+          title: 📝 테스트 커버리지 리포트입니다
+          paths: |
+            ${{ github.workspace }}/api/build/reports/**/jacoco.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          min-coverage-overall: 57.65
+          min-coverage-changed-files: 100
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
